// autogenerated: do NOT edit manually
using Platinum.Configuration;
using System;
using System.Configuration;

namespace Hafnium.Runtime
{
    public partial class RuntimeConfiguration : ConfigurationSection
    {
        public static RuntimeConfiguration Current
        {
            get { return AppConfiguration.SectionGet<RuntimeConfiguration>( "hafnium/runtime" ); }
        }


        [ConfigurationProperty( "content", IsRequired = true )]
        public RuntimeLoaderConfiguration ContentLoader
        {
            get { return (RuntimeLoaderConfiguration) this[ "content" ]; }
            set { this[ "content" ] = value; }
        }
    }


    public partial class RuntimeLoaderConfiguration : ConfigurationElement
    {
        [ConfigurationProperty( "loader", IsRequired = true )]
        public string LoaderMoniker
        {
            get { return (string) this[ "loader" ]; }
            set { this[ "loader" ] = value; }
        }
    }
}

/* eof */
