// autogenerated: do NOT edit manually
using Platinum.Configuration;
using System;
using System.ComponentModel;
using System.Configuration;
using KvConfig = Platinum.Configuration.KeyValueConfigurationElement;
using NullableString = Platinum.Configuration.NullableString;

namespace Hafnium.Runtime
{
    /// <summary />
    public partial class RuntimeConfiguration : ConfigurationSection
    {
        /// <summary>
        /// Gets the configuration instance for section 'hafnium/runtime'
        /// </summary>
        public static RuntimeConfiguration Current
        {
            get { return AppConfiguration.SectionGet<RuntimeConfiguration>( "hafnium/runtime" ); }
        }


        /// <summary />
        [ConfigurationProperty( "content", IsRequired = true )]
        public RuntimeLoaderConfiguration ContentLoader
        {
            get { return (RuntimeLoaderConfiguration) this[ "content" ]; }
            set { this[ "content" ] = value; }
        }


        /// <summary />
        [ConfigurationProperty( "userLookup", IsRequired = true )]
        public UserLookupConfiguration UserLookup
        {
            get { return (UserLookupConfiguration) this[ "userLookup" ]; }
            set { this[ "userLookup" ] = value; }
        }
    }


    /// <summary />
    public partial class RuntimeLoaderConfiguration : ConfigurationElement
    {

        /// <summary />
        [ConfigurationProperty( "loader", IsRequired = true )]
        public string LoaderMoniker
        {
            get { return (string) this[ "loader" ]; }
            set { this[ "loader" ] = value; }
        }


        /// <summary />
        [ConfigurationProperty( "", IsDefaultCollection = true )]
        [ConfigurationCollection( typeof( KvConfig ), AddItemName = "add" )]
        public ConfigurationElementCollection<KvConfig> Settings
        {
            get { return (ConfigurationElementCollection<KvConfig>) base[ "" ]; }
        }
    }


    /// <summary />
    public partial class UserLookupConfiguration : ConfigurationElement
    {

        /// <summary />
        [ConfigurationProperty( "type", IsRequired = true )]
        public string Moniker
        {
            get { return (string) this[ "type" ]; }
            set { this[ "type" ] = value; }
        }


        /// <summary />
        [ConfigurationProperty( "", IsDefaultCollection = true )]
        [ConfigurationCollection( typeof( KvConfig ), AddItemName = "add" )]
        public ConfigurationElementCollection<KvConfig> Settings
        {
            get { return (ConfigurationElementCollection<KvConfig>) base[ "" ]; }
        }
    }

}

/* eof */
