// autogenerated: do NOT edit manually
using Platinum.Configuration;
using System;
using System.Configuration;

namespace Hafnium.WebServices
{
    public partial class WebServicesConfiguration : ConfigurationSection
    {
        public static WebServicesConfiguration Current
        {
            get { return AppConfiguration.SectionGet<WebServicesConfiguration>( "hafnium/webServices" ); }
        }


        [ConfigurationProperty( "namespace", IsRequired = true )]
        public string Namespace
        {
            get { return (string) this[ "namespace" ]; }
            set { this[ "namespace" ] = value; }
        }
    }
}

/* eof */
