// autogenerated: do NOT edit manually
using Platinum.Configuration;
using System;
using System.ComponentModel;
using System.Configuration;
using KvConfig = Platinum.Configuration.KeyValueConfigurationElement;
using NullableString = Platinum.Configuration.NullableString;

namespace Hafnium.WebServices
{
    /// <summary />
    public partial class WebServicesConfiguration : ConfigurationSection
    {
        /// <summary>
        /// Gets the configuration instance for section 'hafnium/webServices'
        /// </summary>
        public static WebServicesConfiguration Current
        {
            get { return AppConfiguration.SectionGet<WebServicesConfiguration>( "hafnium/webServices" ); }
        }


        /// <summary />
        [ConfigurationProperty( "namespace", IsRequired = true )]
        public string Namespace
        {
            get { return (string) this[ "namespace" ]; }
            set { this[ "namespace" ] = value; }
        }
    }

}

/* eof */
